### ISSUE TITLE
MVTyp to opcua_mvf conversion error - autoclosed

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledgepower-filter-pivottoopcua#13]
There is an error when processing the following input MvTyp pivot object:
```
{
   "GTIM":{
      "ComingFrom":"iec104",
      "MvTyp":{
         "mag":{
            "f":27.2999992371
         },
         "q":{
            "Source":"process",
            "Validity":"good"
         },
         "t":{
            "SecondSinceEpoch":1678813311,
            "FractionOfSecond":13388218,
            "TimeQuality":{
               "clockFailure":0,
               "leapSecondKnown":1,
               "timeAccuracy":10
            }
         }
      },
      "Identifier":"MV001",
      "Cause":{
         "stVal":1
      },
      "TmOrg":{
         "stVal":"substituted"
      }
   }
}
```
Error message is:
`Mar 14 11:03:22 f7ca15fac202 Fledge opcuanorth_c1[2433]: WARNING: Mandatory fields from PIVOT are missing for PIVOT ID='MV001' (Missing mask = 0x0080)`

**Comment by jchabod** [comment]
The field "TmValidity" has been defined as mandatory in the interface specification.

I saw that the wiki is not exactly correct for TmOrg and Tmvalidity (it specifies a String whereas as dict with stVal is expected. I corrected it.

**Comment by aklira** [comment]
I confirm that the field "TmValidity" is missing. So this is a problem in incoming the pivot object, that need to be fixed.

**Comment by jchabod** [comment]
There still remains a question: for Sps /Dps the absence of TmValidity does not lead to failure. This needs investigations

**Comment by jchabod** [comment]
Moreover, the wiki must be updated to detail the significance of of "missing mask" values

**Comment by jchabod** [comment]
After review: both tmOrg and TmValidity should be optional. default value = 1st in list.
